-- 코드를 입력하세요
SELECT A.ANIMAL_ID, A.ANIMAL_TYPE, B.NAME FROM ANIMAL_INS A, ANIMAL_OUTS B
WHERE A.ANIMAL_ID = B.ANIMAL_ID
AND SUBSTR(A.SEX_UPON_INTAKE, 0, 3) = 'Int'
AND SUBSTR(B.SEX_UPON_OUTCOME, 0, 3) != 'Int';