-- 코드를 입력하세요
SELECT A.FLAVOR FROM FIRST_HALF A,
(
    SELECT FLAVOR, SUM(TOTAL_ORDER) S_ORDER FROM JULY 
    GROUP BY FLAVOR
) B
WHERE A.FLAVOR = B.FLAVOR
ORDER BY (A.TOTAL_ORDER + B.S_ORDER) DESC
FETCH FIRST 3 ROWS ONLY
;