-- 코드를 입력하세요
SELECT SQ1.ANIMAL_ID, SQ1.NAME
FROM 
    (
        SELECT A.ANIMAL_ID, A.NAME, A.DATETIME AS ATIME, B.DATETIME AS BTIME
        FROM ANIMAL_INS A, ANIMAL_OUTS B
        WHERE A.ANIMAL_ID = B.ANIMAL_ID
    ) SQ1
WHERE SQ1.ATIME > SQ1.BTIME
ORDER BY SQ1.ATIME